# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_image_chaptertask_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='TaskImage',
        ),
    ]
