# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-07 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.CharField(max_length=20000, verbose_name='内容')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='浏览数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发帖人')),
            ],
            options={
                'verbose_name': '论坛信息',
                'verbose_name_plural': '论坛信息',
            },
        ),
        migrations.CreateModel(
            name='DiscussReplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('content', models.CharField(max_length=20000, verbose_name='回复内容')),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_replay', to='coffee_house.DiscussMsg', verbose_name='被回复的帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
            ],
            options={
                'verbose_name': '论坛信息回复',
                'verbose_name_plural': '论坛信息回复',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='小组名称')),
                ('step_info', models.CharField(default='编程基础', max_length=500, verbose_name='小组进度信息')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='小组创建时间')),
                ('in_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClassInfo', verbose_name='小组所在班级')),
            ],
            options={
                'verbose_name': '小组',
                'verbose_name_plural': '小组',
            },
        ),
        migrations.CreateModel(
            name='GroupMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='发送的消息')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.Group', verbose_name='小组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送消息的学生')),
            ],
            options={
                'verbose_name': '学生小组消息',
                'verbose_name_plural': '学生小组消息',
            },
        ),
        migrations.CreateModel(
            name='StudentMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='发送的消息')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('msg_status', models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0, verbose_name='消息状态')),
                ('rev_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_stu', to=settings.AUTH_USER_MODEL, verbose_name='接收消息的学生')),
                ('send_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_stu', to=settings.AUTH_USER_MODEL, verbose_name='发送消息的学生')),
            ],
            options={
                'verbose_name': '学生消息',
                'verbose_name_plural': '学生消息',
            },
        ),
        migrations.CreateModel(
            name='TeacherUserMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='发送的消息')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('msg_type', models.IntegerField(choices=[(0, '学生消息'), (1, '讲师消息')], default=0, verbose_name='消息类型')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生信息')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='老师信息')),
            ],
            options={
                'verbose_name': '老师学生消息',
                'verbose_name_plural': '老师学生消息',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入小组时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.Group', verbose_name='小组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='小组用户')),
            ],
            options={
                'verbose_name': '用户小组表',
                'verbose_name_plural': '用户小组表',
            },
        ),
    ]
