# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('coffee_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherusermsg',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生信息'),
        ),
        migrations.AddField(
            model_name='teacherusermsg',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='老师信息'),
        ),
        migrations.AddField(
            model_name='studentmsg',
            name='rev_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_stu', to=settings.AUTH_USER_MODEL, verbose_name='接收消息的学生'),
        ),
        migrations.AddField(
            model_name='studentmsg',
            name='send_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_stu', to=settings.AUTH_USER_MODEL, verbose_name='发送消息的学生'),
        ),
        migrations.AddField(
            model_name='discussreplay',
            name='discuss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.DiscussMsg', verbose_name='被回复的帖子'),
        ),
        migrations.AddField(
            model_name='discussreplay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复人'),
        ),
        migrations.AddField(
            model_name='discussmsg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发帖人'),
        ),
    ]
