# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-06 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 21, 3, 22, 11905), verbose_name='用户提交时间'),
        ),
    ]
