# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 22, 22, 38, 58, 283250), verbose_name='用户提交时间'),
        ),
    ]
