# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-07 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20180806_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 7, 16, 16, 4, 89349), verbose_name='用户提交时间'),
        ),
    ]
