# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20180825_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 25, 19, 49, 47, 656487), verbose_name='用户提交时间'),
        ),
    ]
