# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-11 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20180807_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 10, 27, 57, 750103), verbose_name='用户提交时间'),
        ),
    ]
