# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_auto_20180831_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkquestion',
            name='question_refer',
            field=models.CharField(default='', max_length=2000, verbose_name='题目参考'),
        ),
        migrations.AlterField(
            model_name='pkquestion',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 12, 30, 17, 821329), verbose_name='用户提交时间'),
        ),
    ]
