# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-11 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_auto_20180811_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 10, 43, 11, 658767), verbose_name='用户提交时间'),
        ),
    ]
