# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_auto_20180903_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpkdetail',
            name='challenger_comp_time',
            field=models.IntegerField(default=0, verbose_name='挑战者完成用时'),
        ),
        migrations.AddField(
            model_name='userpkdetail',
            name='user_comp_time',
            field=models.IntegerField(default=0, verbose_name='用户完成用时'),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 12, 31, 48, 197920), verbose_name='用户提交时间'),
        ),
    ]
