# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 13:49
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='评价内容')),
                ('evaluation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评价时间')),
            ],
            options={
                'verbose_name': '老师评价',
                'verbose_name_plural': '老师评价',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_rankings', models.IntegerField(default=0, verbose_name='班级排名')),
                ('monthly_rankings', models.IntegerField(default=0, verbose_name='月排名')),
                ('total_ranking', models.IntegerField(default=0, verbose_name='总排名')),
                ('total_ranking_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='排名时间')),
                ('estimated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预计完成时间')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
            },
        ),
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(help_text='博客名', max_length=255, verbose_name='博客名')),
                ('blog_body', DjangoUeditor.models.UEditorField(default='', help_text='博客正文', verbose_name='博客正文')),
                ('blog_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户博客',
                'verbose_name_plural': '用户博客',
            },
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_end', models.BooleanField(default=False, help_text='课程是否完成，True或False', verbose_name='课程是否完成')),
                ('chapter_end', models.BooleanField(default=False, help_text='章节是否完成，True或False', verbose_name='章节是否完成')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, help_text='完成时间', verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '用户章节信息',
                'verbose_name_plural': '用户章节信息',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始学习时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('complete', models.BooleanField(default=False, verbose_name='是否学完')),
            ],
            options={
                'verbose_name': '学生课程',
                'verbose_name_plural': '学生课程',
            },
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开通时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '学生专业',
                'verbose_name_plural': '学生专业',
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_info', models.TextField(verbose_name='任务完成说明')),
                ('task_end', models.BooleanField(default=False, verbose_name='任务是否完成')),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to='mission/%Y/%m/%d/', verbose_name='上传文件')),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '用户任务',
                'verbose_name_plural': '用户任务',
            },
        ),
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(help_text='类别', verbose_name='类别')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, help_text='结束时间', verbose_name='结束时间')),
                ('practice_info', models.TextField(default='', help_text='练习题提交答案', verbose_name='练习内容')),
            ],
            options={
                'verbose_name': '学生练习信息',
                'verbose_name_plural': '学生练习信息',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='作业名字', max_length=255, verbose_name='作业名字')),
                ('download', models.FileField(blank=True, help_text='作业下载地址', null=True, upload_to='task/%Y/%m/%d/', verbose_name='作业下载地址')),
                ('complete_time', models.DateTimeField(default=django.utils.timezone.now, help_text='提交时间', verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '学生作业',
                'verbose_name_plural': '学生作业',
            },
        ),
    ]
