# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-26 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relationship', '0001_initial'),
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='chapter',
            field=models.ForeignKey(help_text='章节id', on_delete=django.db.models.deletion.CASCADE, to='major.Chapter', verbose_name='章节名'),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='practice',
            field=models.ForeignKey(help_text='练习题id', on_delete=django.db.models.deletion.CASCADE, to='major.Practice', verbose_name='练习名'),
        ),
        migrations.AddField(
            model_name='userpractice',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生名'),
        ),
        migrations.AddField(
            model_name='usermission',
            name='chapter',
            field=models.ForeignKey(help_text='章节id', on_delete=django.db.models.deletion.CASCADE, to='major.Chapter', verbose_name='章节id'),
        ),
        migrations.AddField(
            model_name='usermission',
            name='mission',
            field=models.ForeignKey(help_text='任务id', on_delete=django.db.models.deletion.CASCADE, to='major.ChapterTask', verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='usermission',
            name='user',
            field=models.ForeignKey(help_text='用户名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='usermajor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Major', verbose_name='专业名'),
        ),
        migrations.AddField(
            model_name='usermajor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生名'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.Major', verbose_name='课程名'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生名'),
        ),
        migrations.AddField(
            model_name='userchapter',
            name='chapter',
            field=models.ForeignKey(help_text='章节id', on_delete=django.db.models.deletion.CASCADE, to='major.Chapter', verbose_name='章节名'),
        ),
        migrations.AddField(
            model_name='userchapter',
            name='course',
            field=models.ForeignKey(help_text='课程id', on_delete=django.db.models.deletion.CASCADE, to='major.Major', verbose_name='课程名'),
        ),
        migrations.AddField(
            model_name='userchapter',
            name='user',
            field=models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生名'),
        ),
        migrations.AddField(
            model_name='userblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='mission',
            field=models.ForeignKey(help_text='任务id', on_delete=django.db.models.deletion.CASCADE, to='major.ChapterTask', verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='teacher',
            field=models.ForeignKey(help_text='老师id', on_delete=django.db.models.deletion.CASCADE, to='users.Teacher', verbose_name='老师id'),
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='user',
            field=models.ForeignKey(help_text='用户名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='userchapter',
            unique_together=set([('user', 'chapter')]),
        ),
    ]
