# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_relationship', '0002_auto_20180826_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherevaluation',
            old_name='teacher_name',
            new_name='teacher',
        ),
    ]
