# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_relationship', '0002_auto_20180826_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpractice',
            name='count',
            field=models.IntegerField(default=0, help_text='练习题提交次数', verbose_name='作业提交次数'),
        ),
    ]
