# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('user_relationship', '0003_auto_20180826_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherevaluation',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='major.ChapterTask', verbose_name='任务id'),
            preserve_default=False,
        ),
    ]
