# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_relationship', '0004_teacherevaluation_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='user_mission_name',
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
